In [1]:
import torch
import numpy as np

In [2]:
from numpy.core.fromnumeric import size
# Создайте случайный FloatTensor размера 3x4x5
a = np.random.randint(0, 5, size=(3, 4, 5))
b = torch.FloatTensor(a)
print(a)
print(f'Размер: {a.shape}')
print(f'Тип: {a.dtype }')
print(b)
print(f'Размер: {b.size()}')
print("Количество измерений: %s" % b.dim())
print("Тип: %s\n" % (b.type()))

[[[0 4 1 2 0]
  [0 4 3 4 0]
  [4 3 3 4 1]
  [4 3 4 2 4]]

 [[1 2 4 3 4]
  [3 1 1 1 3]
  [3 0 4 1 0]
  [0 3 0 2 3]]

 [[2 2 0 3 2]
  [0 2 3 1 0]
  [2 4 4 2 1]
  [0 4 4 2 0]]]
Размер: (3, 4, 5)
Тип: int64
tensor([[[0., 4., 1., 2., 0.],
         [0., 4., 3., 4., 0.],
         [4., 3., 3., 4., 1.],
         [4., 3., 4., 2., 4.]],

        [[1., 2., 4., 3., 4.],
         [3., 1., 1., 1., 3.],
         [3., 0., 4., 1., 0.],
         [0., 3., 0., 2., 3.]],

        [[2., 2., 0., 3., 2.],
         [0., 2., 3., 1., 0.],
         [2., 4., 4., 2., 1.],
         [0., 4., 4., 2., 0.]]])
Размер: torch.Size([3, 4, 5])
Количество измерений: 3
Тип: torch.FloatTensor



In [3]:
# Выведите его форму (shape)
b.size()

torch.Size([3, 4, 5])

In [4]:
# Приведите его к форме 6 X 10
c = b.view(6, 10)
print(c)
print(c.size())

tensor([[0., 4., 1., 2., 0., 0., 4., 3., 4., 0.],
        [4., 3., 3., 4., 1., 4., 3., 4., 2., 4.],
        [1., 2., 4., 3., 4., 3., 1., 1., 1., 3.],
        [3., 0., 4., 1., 0., 0., 3., 0., 2., 3.],
        [2., 2., 0., 3., 2., 0., 2., 3., 1., 0.],
        [2., 4., 4., 2., 1., 0., 4., 4., 2., 0.]])
torch.Size([6, 10])


In [5]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
vect = torch.tensor([1, 4, 2, 2, 1])
res = torch.mul(b, vect)
print(f'First variant:\n {res}\n')
print(f'Second variant:\n {b * vect}')

First variant:
 tensor([[[ 0., 16.,  2.,  4.,  0.],
         [ 0., 16.,  6.,  8.,  0.],
         [ 4., 12.,  6.,  8.,  1.],
         [ 4., 12.,  8.,  4.,  4.]],

        [[ 1.,  8.,  8.,  6.,  4.],
         [ 3.,  4.,  2.,  2.,  3.],
         [ 3.,  0.,  8.,  2.,  0.],
         [ 0., 12.,  0.,  4.,  3.]],

        [[ 2.,  8.,  0.,  6.,  2.],
         [ 0.,  8.,  6.,  2.,  0.],
         [ 2., 16.,  8.,  4.,  1.],
         [ 0., 16.,  8.,  4.,  0.]]])

Second variant:
 tensor([[[ 0., 16.,  2.,  4.,  0.],
         [ 0., 16.,  6.,  8.,  0.],
         [ 4., 12.,  6.,  8.,  1.],
         [ 4., 12.,  8.,  4.,  4.]],

        [[ 1.,  8.,  8.,  6.,  4.],
         [ 3.,  4.,  2.,  2.,  3.],
         [ 3.,  0.,  8.,  2.,  0.],
         [ 0., 12.,  0.,  4.,  3.]],

        [[ 2.,  8.,  0.,  6.,  2.],
         [ 0.,  8.,  6.,  2.,  0.],
         [ 2., 16.,  8.,  4.,  1.],
         [ 0., 16.,  8.,  4.,  0.]]])


In [6]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
c_ = c.T
res_2 = torch.mm(c, c_)
print(res_2)
print(res_2.size())

tensor([[ 62.,  55.,  29.,  26.,  35.,  60.],
        [ 55., 112.,  71.,  53.,  48.,  73.],
        [ 29.,  71.,  67.,  36.,  29.,  46.],
        [ 26.,  53.,  36.,  48.,  17.,  40.],
        [ 35.,  48.,  29.,  17.,  35.,  42.],
        [ 60.,  73.,  46.,  40.,  42.,  77.]])
torch.Size([6, 6])


In [30]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x=torch.tensor(1.0,requires_grad=True)
z=torch.tensor(0.5,requires_grad=True)
t=torch.tensor(2.0,requires_grad=True)
y=x**3 + z - 75*t

y.backward()  

print(x.grad)
print(z.grad)
print(t.grad)

tensor(3.)
tensor(1.)
tensor(-75.)


In [32]:
import sympy as sym
# create a "symbols"
x_ , z_, t_ = sym.symbols('x z t')
f = x_**3 + z_ - 75*t_

#Differentiating partially 
derivative_f_x = f.diff(x_)
derivative_f_z = f.diff(z_)
derivative_f_t = f.diff(t_)
print(derivative_f_x)
print(derivative_f_z)
print(derivative_f_t)

3*x**2
1
-75


In [15]:
# Создайте единичный тензор размера 5x6
d = torch.ones(5,6)
d

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [16]:
# Переведите его в формат numpy
d = d.numpy()
print(d)
print(type(d))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [10]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 


Так и не понял последнего задания...